version: '3'
services:

  server:
    build: .
    container_name: NapoleonHomework
    ports:
    - "8000:8000"
    command: sh -c "cd /NapoleonHomework
             && alembic upgrade head
             && python main.py"
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    container_name: NapoleonHW-db
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"