"""user board fix

Revision ID: 9df8a2030321
Revises: e675d46d285e
Create Date: 2021-01-27 01:54:36.701593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df8a2030321'
down_revision = 'e675d46d285e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
